name: tasklink
description: AI-driven platform connecting job seekers with recruiters for full-time job opportunities.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # Use supabase and supabase_flutter separately to avoid sign_in_with_apple
  supabase: ^1.11.11
  gotrue: ^1.12.6
  provider: ^6.1.1
  #file_picker: ^6.1.1
  path_provider: ^2.1.1
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  flutter_spinkit: ^5.2.0
  # Charts for analytics dashboard
  fl_chart: ^0.62.0
  # For date handling in analytics
  timeago: ^3.6.0
  # For sharing analytics and reports
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - .env